# Generated by Django 5.2.11 on 2026-02-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='class_range',
            field=models.CharField(blank=True, help_text='e.g. Class LKG - 8, Class 3 - 13', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='audience',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('KIDS', 'Kids')], default='STUDENT', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='class_range',
            field=models.CharField(blank=True, help_text='e.g. LKG - 8, Class 3 - 12', max_length=50),
        ),
    ]
