# Generated by Django 5.2.11 on 2026-02-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('ENROLLMENT', 'Enrollment Report'), ('COMPLETION', 'Completion Rate'), ('REVENUE', 'Revenue Report'), ('PERFORMANCE', 'Student Performance')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
